### ISSUE TITLE
[客户列表页]子标签[设计 | 工程]的区分 进行到工程的客户不在设计中显示

### ISSUE THREAD

**Issue by ShenZZ** [ShenZZ/HomeSolution#126]
同步订单的完结状态 
进行中客户子标签[设计 | 工程 | 产品 | 定制] 查询时判断订单是否完结

> 问题: 如果所有订单已完结 子标签中都不会显示客户 怎么解决?

**Comment by kzxiawei** [comment]
如果所有订单都完结的客户，可以单独归一类，“待完结”，如果产生新的订单，则不显示在“待完结”中。有几种情况：
1、设计订单点了完结，施工订单没有生成；
2、客户项目结束，点施工订单完结，在客户列表中找不到该客户；

**Comment by ShenZZ** [comment]
这个方案有点复杂

可以在[设计]中添加选项是否[含进行到工程的客户] 默认不选择
