### ISSUE TITLE
关于订金、收款的统计要求

### ISSUE THREAD

**Issue by qianzhou009** [ShenZZ/HomeSolution#13]
当⽉月订⾦金金收款=当⽉月实收订⾦金金的总额
当⽉月结转收⼊入=当⽉月合同状态调整为“已结转”的项⽬目
当⽉月下单销售额=当⽉月采购单调整为“已付款”的销售额合计

**Comment by ShenZZ** [comment]
这个问题不清楚 回头具体做统计报表时再讨论
