### ISSUE TITLE
关于采购成本统计表

### ISSUE THREAD

**Issue by qianzhou009** [ShenZZ/HomeSolution#14]
采购成本统计表按照项⽬目销售单、采购单对应，按项⽬目统计合计成本率、按照品牌统计、按照项⽬目/品牌统计，⼈人⼯工费及物流费⽤用可以⽤用采购单加进去

**Comment by ShenZZ** [comment]
[采购成本数据分析.xlsx](https://github.com/ShenZZ/HomeSolution/files/3572598/default.xlsx)
按客户合计 按供应商合计 2张表供参考
