### ISSUE TITLE
编辑客户资料无法进行下一步操作

### ISSUE THREAD

**Issue by qianzhou009** [ShenZZ/HomeSolution#17]
编辑客户资料——重新选择小区——输入小区名称后没有弹出小区列表，无法选择。

![image](https://user-images.githubusercontent.com/53465079/62110527-34849280-b2e1-11e9-8bf1-d4bd5727996b.png)

**Comment by ShenZZ** [comment]
可能是网络问题 具体需要详细测试 考虑解决方案 
暂时不处理
