### ISSUE TITLE
阶段完结时 同时完成所有子事项

### ISSUE THREAD

**Issue by ShenZZ** [ShenZZ/HomeSolution#2]
点击阶段完结时 同时设置所有子事项完成

数据库历史数据处理 已经阶段完结的事项

todo: 项目完结时是否要完结所有的阶段和事项?

**Comment by jerivs** [comment]
已修改。
阶段完结时，事项同时完成(未完成且有负责人的事项)。
项目完结时，已进行的阶段同时完结。
