### ISSUE TITLE
商品价格显示格式不合适。

### ISSUE THREAD

**Issue by qianzhou009** [ShenZZ/HomeSolution#22]
建议修改为：标准销售价和标准采购价。
![image](https://user-images.githubusercontent.com/53465079/62111828-0eacbd00-b2e4-11e9-8029-47b2b092536f.png)

**Comment by ShenZZ** [comment]
这个回头放到 产品价格维护中一起修改

### 产品价格维护方案

- 供应商推荐价格
- 公司销售价 (推荐价格*比例)
- 公司采购价 (推荐价格*比例)
- 按供应商和品类设置的比例问题 todo
- ui设计
