### ISSUE TITLE
销售订单详情中的【采购订单】列表，采购订单缺少详情链接

### ISSUE THREAD

**Issue by qianzhou009** [ShenZZ/HomeSolution#24]
![image](https://user-images.githubusercontent.com/53465079/62114255-d9ef3480-b2e8-11e9-909f-edbbbdd23e9b.png)

**Comment by ShenZZ** [comment]
这里的采购清单不可以显示采购价等信息 
点击链接展开详情也不可以显示采购价
这个和订单和采购列表页有区分 主要设计权限问题 

具体怎么设计 这里应该怎么显示 需要设计

**Comment by ShenZZ** [comment]
> 这里的采购单分两个概念: 1.合同拆分的子订单 2.子订单对应的采购单

1. 在客户和订单列表页中 点击订单打开时显示子订单信息 (包含采购价等采购数据)
2. 在采购单列表页 直接打开显示采购单详情 含采购数据

**Comment by ShenZZ** [comment]
#32
