### ISSUE TITLE
日志查看页的设计 (客户 阶段看板 事项看板弹窗显示)

### ISSUE THREAD

**Issue by kzxiawei** [ShenZZ/HomeSolution#26]

**Comment by kzxiawei** [comment]
目前只能显示项目日记，需要查看客户日记

<img width="1019" alt="屏幕快照 2019-08-01 下午12 59 33" src="https://user-images.githubusercontent.com/53504443/62267172-db8e3900-b45d-11e9-99f5-b588f8868e3a.png">

**Comment by ShenZZ** [comment]
### 日志有几个地方查看:

1. 客户列表页打开弹窗显示日志
2. 项目阶段详情页下方 显示本阶段的日志
3. 项目阶段看板点击弹窗显示日志
4. 按员工汇总查看日志

1和3 可以统一考虑一个弹窗页面 默认显示客户或阶段关联的 可以选择全部 系统 等
todo: @qianzhou009 钱胄可以考虑下弹窗页

**Comment by qianzhou009** [comment]
- 采用通用日志页面，可根据日志类型、项目、阶段进行条件筛选：
界面原型如下：
![image](https://user-images.githubusercontent.com/53465079/62449193-42805a80-b79c-11e9-9dbe-327f362d114d.png)
详见
https://6nhqwx.axshare.com/#g=1&p=客户详情
https://6nhqwx.axshare.com/#g=1&p=项目进度-客户
https://6nhqwx.axshare.com/#g=1&p=阶段详情
 -  可根据不同页面传入不同的参数，调整筛选条件
客户id（必选）  ；日志类型（可选：全部、客户、项目、系统）；项目（可选：项目ID）；阶段（可选：阶段名称）

**Comment by ShenZZ** [comment]
1. 日志查看做成通用组件
2. 可以按 全部,客户,项目,[XXX项目],系统,[任务] 进行筛选
