### ISSUE TITLE
[订单详情]中按权限区分显示[子订单列表]或[采购单列表] (显示销售价或采购价)

### ISSUE THREAD

**Issue by ShenZZ** [ShenZZ/HomeSolution#32]
### [订单详情]中显示[子订单列表](=采购单 显示拆单后的销售价和状态 不显示采购价)
重构订单详情页中采购清单页面 新增子订单详情页(类似于采购单详情)

1. 添加子订单列表页 (显示拆单后的销售价和状态 不显示采购价)
2. 添加子订单详情页 (同上 不显示采购价)

todo: 页面细节需设计 @qianzhou009

**Comment by qianzhou009** [comment]
原型参考：
https://6nhqwx.axshare.com/#g=1&p=销售订单列表

**Comment by ShenZZ** [comment]
1. [订单详情页] > [采购清单]: 按权限判断 显示[采购价]或[销售价]/ 链接跳转[子订单详情页]或[采购单]
2. [订单列表页]点击链接: 按权限判断 弹窗[子订单清单]或者[采购清单]
3. 添加[子订单详情页] 只查看无操作
