### ISSUE TITLE
销售单迭代

### ISSUE THREAD

**Issue by kzxiawei** [ShenZZ/HomeSolution#58]
客户下拉：选择销售单列表内的客户，在客户栏录⼊数据也是定位销售单列表内的客户
排序按照客户排，已完结的客户排到后⾯，或者增加查询条件筛选
销售单的开始、完⼯时间在⽣成销售单的时候还不清楚，在销售单确定的时候才清楚，最好要开放编辑
产品订单、定制产品订单的名称不够准确，改为软装订单、定制订单，（以后可以扩充设备订单、主材订单、家电订
单）
把项⽬管理中的阶段链接到销售单列表⾥

- 客户下拉列表
- 销售单排序
- 销售单开始、完工时间的维护
- 销售单类型维护
- 项目管理的链接

**Comment by kzxiawei** [comment]
<img width="923" alt="屏幕快照 2019-09-20 下午6 07 47" src="https://user-images.githubusercontent.com/53504443/65319266-c61dcb80-dbd1-11e9-99d2-57d8d381ba3a.png">
销售单列表页的拆单链接页需要加上采购单的完成时间，便于安装和销售查询。

**Comment by kzxiawei** [comment]
<img width="1022" alt="屏幕快照 2019-09-20 下午6 20 13" src="https://user-images.githubusercontent.com/53504443/65319934-5f99ad00-dbd3-11e9-920b-910a101d8fc2.png">
-销售单详情页的采购清单需要加上完成时间。

**Comment by ShenZZ** [comment]
##### 关于订单修改:
[ ] 替换完工日期 改成订单周期 [X周] 
[ ] 订单添加签单日期 默认设置开始日期=签单日期 完结日期=签单日期+周期
[ ] 销售单列表页 小区客户和开始结束日期 对调 
[ ] 开始结束日期旁边添加修改按钮 可以录入订单开始结束日期
[ ] 采购单列表添加完结日期

**Comment by kzxiawei** [comment]
1、在销售单里增加一个“加急单”标签，人工操作；实际应用时会出现客户加急要求的销售单，需要重点盯控；
2、延期标记：当销售单结束时间超过当前时间，系统自动标价延期单；
3、账单打印：客户交款前打印，交客户签字确认，具体形式跟财务、销售商量确定；
4、销售单打印中增加一个数量清单打印的选项，主要是针对五金清单打印，目前打印出来的格式有两个问题，一是没有五金的商品也会显示名称和总价，会有歧义，另外因为折扣不同，部分五金的价格会不一样，不便外流，只要打印一份五金的数量清单即可。
