### ISSUE TITLE
[客户管理] 修改客户状态和标签管理

### ISSUE THREAD

**Issue by kzxiawei** [ShenZZ/HomeSolution#64]
把客户分类调整一下
第一页客源：未进店、已进店、意向，作废，前三类状态可以切换，
进店储备改为“储备”
取消“加入客户”，收取定金后客源自动转到客户里
取消删除功能，改为“作废”
第二页客户：定金、设计、工程、产品（定制、标准）全部（最好是项目中没有的订单类型就不显示）
把产值储备和收款储备分成两列，产值储备跟项目类型关联，可以按类型统计，收款储备项目不需维护，直接调取预收款项目
项目操作完结时，要查销售单是否完结、采购单是否全部完结、款项是否结平、项目是否已经全部完结，录入保修开始、结束时间，转到“保修”
第三页完结：保修、维修、退单
保修期到，系统提示标签，到期自动改为“维修”

**Comment by ShenZZ** [comment]
#### 客户管理页标签:

- 客源
- - 全部
- - 未进店
- - 已进店
- - 意向 (默认选择)
- - 作废
- 客户 (客户不可以退回客源 不可以作废 只有[完结]功能 有订单完结时转入保修 无订单完结转入退单)
- - 全部 (默认选择)
- - 定金
- - 设计
- - 工程
- - 产品
- - 定制
- 完结
- - 保修
- - 历史
- - 退单
